version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  browser-tools: circleci/browser-tools@2.1.0
  node: circleci/node@7.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:24.11-browsers
  docker-python:
    docker:
      - image: cimg/python:3.12

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  # install-dependencies:
  # executor: node-executor
  # steps:
  # - checkout
  # - node/install-packages:
  # pkg-manager: yarn

  build-deploy-dr:
    executor: node-executor
    steps:
      - *attach_workspace
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - aws-cli/install
      - run:
          name: deploy
          command: |
            export NODE_ENV=production
            export NEXT_PUBLIC_NODE_ENV=production
            export NEXT_PUBLIC_ENV_NAME=production
            export NEXT_PUBLIC_REPAIRS_HUB_URL=https://repairs-hub.hackney.gov.uk/work-orders
            export NEXT_PUBLIC_FIRST_WEEK=2021-11-01
            export NEXT_PUBLIC_OVERTIME_HOURS_TYPE_ID=400
            export NEXT_PUBLIC_OVERTIME_JOB_TYPE_ID=401
            export NEXT_PUBLIC_OVERTIME_RATE=24.34
            export NEXT_PUBLIC_OOH_ROTA_TYPE_ID=500
            export NEXT_PUBLIC_OOH_JOB_TYPE_ID=501
            export NEXT_PUBLIC_OOH_RATE=27.51
            export NEXT_PUBLIC_SENTRY_ENVIRONMENT=production
            export NEXT_PUBLIC_SENTRY_RELEASE=$CIRCLE_SHA1
            export NEXT_PUBLIC_SENTRY_DEBUG=false
            export NODE_OPTIONS=--openssl-legacy-provider

            yarn build
            rm -rf node_modules
            cd lambda
            yarn install --production --frozen-lockfile
            cd ..
            npx --yes serverless deploy --stage production

  assume-role-dr:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_DISASTER_RECOVERY
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  continuous-delivery:
    jobs:
      # - install-dependencies
      - permit-deploy-dr:
          type: approval
      - assume-role-dr:
          context: api-assume-role-disaster-recovery-context
          requires:
            - permit-deploy-dr
      - build-deploy-dr:
          requires:
            - assume-role-dr
          context:
            - 'Serverless Framework'
